name: Java CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - refs/tags/*
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8.0.452+9'
    - name: Build
      run: ./gradlew check
